### PR TITLE
Add adopters list seed

### PR DESCRIPTION
**Pull request by jozic**
The idea is to create the list of Adopters that use Monix in production, similar to what [Cats has in README](https://github.com/typelevel/cats/blob/master/README.md#adopters).
The motivation is to promote the library and make people feel more confident using it.
Thanks everyone!

### CODE REVIEW

**Comment by Avasil** [comment]
I'm 👍 for such a list, I'm sometimes asked about it but I don't know who actually uses Monix. :D 

There used to be this issue: https://github.com/monix/monix/issues/233

**Comment by Krever** [comment]
I'm not sure how you want this to work, but you can put Sony Electronics on the list as well :)

**Comment by yanns** [comment]
As asked on Gitter, we, at commercetools, are using Monix in production.
If you need more info, please feel free to ask!

**Comment by mdedetrich** [comment]
We also use Monix Task in Zalando SE, also ping/email if you need more info

**Comment by jozic** [comment]
@Krever @yanns @mdedetrich 
thank you guys!
 as I wrote in the comment to this PR, i want to have a list with adopters (company names and links to their sites) same way cats library has one
Could you please edit your posts and add links to your company website? I can google them by names, but to avoid any mistakes would prefer you type them yourselves. Then i will update the PR
hopefully once we have like 5 companies, we can merge and let the list grow by itself

**Comment by jozic** [comment]
@Krever @yanns Thanks! Updated PR with the details you provided
@mdedetrich should I use `https://www.zalando.com/`? Is `Zalando SE` is same as `Zalando`?

**Comment by macalinao** [comment]
Hey all, we at Abacus use Monica in production.
https://abacusfi.com

**Comment by mdedetrich** [comment]
@jozic Yes it is (Zalando SE is just the public listed company name on the stock exchange). There is also https://jobs.zalando.com/tech/ which you can refer to

**Comment by jozic** [comment]
@Avasil can we merge this now? Five companies looks like a good start to me, wdys?

cc @alexandru @oleg-py

**Comment by Avasil** [comment]
Sure @jozic :)

**Comment by jozic** [comment]
thanks!

**Pull request merged**
