### PR TITLE
[WIP] Tracing Scheduler

### PR DESCRIPTION
**Pull request by leandrob13**
An attempt to solve #246 by adding a implementations of `LocalContext`, based on finagle's implementation, `TracingScheduler` and `TaskTracedRunLoop` for propagation of locals. Using the CorrelationId Tracing context we can do the following:

Example in [tests](https://github.com/leandrob13/monix/blob/feature/tracingScheduler/monix-eval/jvm/src/test/scala/monix/execution/misc/CorrelationIdSuite.scala)
```scala
    def taskFlatMap(implicit sc: Scheduler): Task[(Int, Option[CorrelationId])] = {
      for {
        a <- Task.fromFuture(Future(1))
        b <- Task.fromFuture(Future(1))
        c <- Task.fromFuture(Future(1))
        d <- Task.pure(CorrelationId.current)
      } yield (a + b + c, d)
    }

    val t1 = CorrelationId("1111").asCurrent {
      import monix.execution.Scheduler.Implicits.global
      // Works with normal AsyncScheduler and runAsyncTraced
      taskFlatMap.runAsyncTraced
    }
    val (_, cid1) = Await.result(t1, 10.seconds)
    assert(cid1.contains(CorrelationId("1111")))

    val t2 = CorrelationId("1111").asCurrent {
      import monix.execution.schedulers.TracingScheduler.Implicits.traced
      // Works with TracingScheduler and runAsync
      taskFlatMap.runAsync
    }
    val (_, cid2) = Await.result(t2, 10.seconds)
    assert(cid2.contains(CorrelationId("1111")))
```

Currently a WIP.

### CODE REVIEW

**Comment by alexandru** [comment]
@leandrob13 I don't think this will work well.

This is indeed a problem of transporting those values over asynchronous boundaries, but you don't have a guarantee that your tracing scheduler will be charge.

```scala
// Stupid sample to illustrate a point
val tick: Task[Unit] = Task.unsafeCreate { (ctx, cb) => 
  import java.util.concurrent.Executors
  val ec = Executors.newSingleThreadExecutor() 

  ec.execute(new Runnable () {
    def run() = {
      try cb(Success(())) finally ec.shutdown()
    }
  })
}
```

In this example `doStuff` basically does its own thing and you have no way of knowing that you have an async boundary in it.

This is why, if you're going to implement something that works with `Task`, then the restore of those values has to happen when that `cb(Success(()))` call is made above, which in the implementation ends up executing the continuation of the run-loop. Such that this can work ...

```scala
tick.flatMap(_ => Task.pure(TracingContext.value))
```

In case the problem isn't clear, in this `tick.flatMap(...)` call, the `TracingScheduler` that you described is not involved at all. Yes, we receive its reference in `Task.unsafeCreate` in that `ctx` that's injected, but we are not using it.

Also pay attention to laziness. A construct like this can't work because with `Task` nothing gets executed yet:

```scala
TracingContext.withValue(Map("xID" -> "1234")) {
  Task(println(s"Log this map ${TracingContext.value}"))
}
```

**Comment by alexandru** [comment]
@leandrob13 btw, nice to see you working on this 🙂

**Comment by leandrob13** [comment]
@alexandru so defining a new scheduler to catch a context is not the way to go for `Task`? Or is is the way I am doing it with `DynamicVariable`? I understand your point and it seems I will have to focus my efforts on `TaskRunLoop` where I am guessing it might get messy. 

I am thinking of keeping the scheduler to see how it plays along with scala Futures and do some changes just to experiment. I am thinking of two other approaches: 
-Try it with java's `ThreadLocal`.
-Implementing a `Local` like in finagle.

Thanks for the pointers! And expect more questions!

**Comment by leandrob13** [comment]
@alexandru I made some progress with the LocalContext implementation. I used the tick example you gave me and it seems to be propagating it using only the TracingScheduler. I couldn't make it work with the new `TaskTracedRunLoop`, considering I was passing the local until the las part of the `onFinish` execution.

The tests are [here](https://github.com/leandrob13/monix/blob/feature/tracingScheduler/monix-eval/shared/src/test/scala/monix/execution/misc/CorrelationIdSuite.scala)

and the implementation of [TaskTracedRunLoop](https://github.com/leandrob13/monix/blob/feature/tracingScheduler/monix-eval/shared/src/main/scala/monix/eval/internal/TaskTracedRunLoop.scala)

**Comment by leandrob13** [comment]
@alexandru I have some working [tests](https://github.com/leandrob13/monix/blob/feature/tracingScheduler/monix-eval/shared/src/test/scala/monix/execution/misc/CorrelationIdSuite.scala) that you can review now. It works with your tick example. I had a bug in the `LocalContext` implementation, it is fixed now.

I think I am getting closer, just need to check more scenarios to test.

**Comment by leandrob13** [comment]
Closing it, I opened a cleaner PR in #429.

**Pull request closed without merging**
