### PR TITLE
Extend ObservableLike with filterNot method (#800)

### PR DESCRIPTION
**Pull request by Otah**
Introducing `ObservableLike.filterNot` operation for 2.x series.

### CODE REVIEW

**Comment by alexandru** [comment]
All code needs some test. Can you add a test?

Also if we add `filterNot` in 2.3, we need it in 3.0 as well.

**Comment by Otah** [comment]
Ah, yes, sorry for not adding the test. I will add it.

Regarding the 3.0, that’s my plan. However because in 3 series there is not only the simple `filter(A=>Boolean)` but also variants with `Task`, I haven’t yet had a chance to implement this for consistency.

Long story short, I will do both the tests and a separate PR for 3 series (to `master`, correct me if I am wrong). For now, I just need some time to do it.

Thanks!

**Comment by alexandru** [comment]
I wouldn't worry about the `Task` variant in 3.0.

**Comment by Otah** [comment]
Not sure why the build failed, seems like the Travis CI somehow timed out? The SBT build was passing locally.

I have opened a MR for series 3.x as well, see https://github.com/monix/monix/pull/819

**Comment by Avasil** [comment]
Thank you @Otah :)

**Pull request merged**
