### PR TITLE
add Iterant.lastOptionL

### PR DESCRIPTION
**Pull request by volth**
There is ```Iterant.headOptionL``` but no ```Iterant.lastOptionL```

### CODE REVIEW

**Comment by alexandru** [comment]
That's cool, but it needs a test.

**Comment by alexandru** [comment]
A very simple test, nothing complicated.

**Comment by volth** [comment]
@alexandru I copied ```IterantHeadOptionSuite.scala``` with just ```s/head/last/g```

**Comment by Avasil** [comment]
Thanks @volth !

**Pull request merged**
