### PR TITLE
Observable drop long

### PR DESCRIPTION
**Pull request by gclaramunt**
See https://github.com/monix/monix/issues/1072

### CODE REVIEW

**Comment by Avasil** [comment]
Thanks for PR @gclaramunt sorry for not following up on it earlier

Unfortunately the change is not binary compatible so we can't replace it until `4.x`

I don't remember the issue about the overloads, I will try to dig it up

I suppose we are stuck with separate method name unless we can find a way to make it compatible

**Comment by gclaramunt** [comment]
Ah, sorry I missed the binary check... I'll try to check the issue too, it might not be a big deal.
Otherwise, I'll change it to dropLong

**Comment by gclaramunt** [comment]
Here are the issues with overloading: https://stackoverflow.com/questions/2510108/why-avoid-method-overloading but I've tested and it doesn't happen with Int and Long (it picks int).
Still, it might be risky ... let me know if you want to got with dropLong or something else

**Comment by gclaramunt** [comment]
cool, thanks! :)

**Pull request merged**
